<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class ProvinciaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [ 'id' => '0101', 'name' => 'Chachapoyas', 'departamentos_id' => '01' ]
            ,[ 'id' => '0102', 'name' => 'Bagua', 'departamentos_id' => '01' ]
            ,[ 'id' => '0103', 'name' => 'Bongará', 'departamentos_id' => '01' ]
            ,[ 'id' => '0104', 'name' => 'Condorcanqui', 'departamentos_id' => '01' ]
            ,[ 'id' => '0105', 'name' => 'Luya', 'departamentos_id' => '01' ]
            ,[ 'id' => '0106', 'name' => 'Rodríguez de Mendoza', 'departamentos_id' => '01' ]
            ,[ 'id' => '0107', 'name' => 'Utcubamba', 'departamentos_id' => '01' ]
            ,[ 'id' => '0201', 'name' => 'Huaraz', 'departamentos_id' => '02' ]
            ,[ 'id' => '0202', 'name' => 'Aija', 'departamentos_id' => '02' ]
            ,[ 'id' => '0203', 'name' => 'Antonio Raymondi', 'departamentos_id' => '02' ]
            ,[ 'id' => '0204', 'name' => 'Asunción', 'departamentos_id' => '02' ]
            ,[ 'id' => '0205', 'name' => 'Bolognesi', 'departamentos_id' => '02' ]
            ,[ 'id' => '0206', 'name' => 'Carhuaz', 'departamentos_id' => '02' ]
            ,[ 'id' => '0207', 'name' => 'Carlos Fermín Fitzcarrald', 'departamentos_id' => '02' ]
            ,[ 'id' => '0208', 'name' => 'Casma', 'departamentos_id' => '02' ]
            ,[ 'id' => '0209', 'name' => 'Corongo', 'departamentos_id' => '02' ]
            ,[ 'id' => '0210', 'name' => 'Huari', 'departamentos_id' => '02' ]
            ,[ 'id' => '0211', 'name' => 'Huarmey', 'departamentos_id' => '02' ]
            ,[ 'id' => '0212', 'name' => 'Huaylas', 'departamentos_id' => '02' ]
            ,[ 'id' => '0213', 'name' => 'Mariscal Luzuriaga', 'departamentos_id' => '02' ]
            ,[ 'id' => '0214', 'name' => 'Ocros', 'departamentos_id' => '02' ]
            ,[ 'id' => '0215', 'name' => 'Pallasca', 'departamentos_id' => '02' ]
            ,[ 'id' => '0216', 'name' => 'Pomabamba', 'departamentos_id' => '02' ]
            ,[ 'id' => '0217', 'name' => 'Recuay', 'departamentos_id' => '02' ]
            ,[ 'id' => '0218', 'name' => 'Santa', 'departamentos_id' => '02' ]
            ,[ 'id' => '0219', 'name' => 'Sihuas', 'departamentos_id' => '02' ]
            ,[ 'id' => '0220', 'name' => 'Yungay', 'departamentos_id' => '02' ]
            ,[ 'id' => '0301', 'name' => 'Abancay', 'departamentos_id' => '03' ]
            ,[ 'id' => '0302', 'name' => 'Andahuaylas', 'departamentos_id' => '03' ]
            ,[ 'id' => '0303', 'name' => 'Antabamba', 'departamentos_id' => '03' ]
            ,[ 'id' => '0304', 'name' => 'Aymaraes', 'departamentos_id' => '03' ]
            ,[ 'id' => '0305', 'name' => 'Cotabambas', 'departamentos_id' => '03' ]
            ,[ 'id' => '0306', 'name' => 'Chincheros', 'departamentos_id' => '03' ]
            ,[ 'id' => '0307', 'name' => 'Grau', 'departamentos_id' => '03' ]
            ,[ 'id' => '0401', 'name' => 'Arequipa', 'departamentos_id' => '04' ]
            ,[ 'id' => '0402', 'name' => 'Camaná', 'departamentos_id' => '04' ]
            ,[ 'id' => '0403', 'name' => 'Caravelí', 'departamentos_id' => '04' ]
            ,[ 'id' => '0404', 'name' => 'Castilla', 'departamentos_id' => '04' ]
            ,[ 'id' => '0405', 'name' => 'Caylloma', 'departamentos_id' => '04' ]
            ,[ 'id' => '0406', 'name' => 'Condesuyos', 'departamentos_id' => '04' ]
            ,[ 'id' => '0407', 'name' => 'Islay', 'departamentos_id' => '04' ]
            ,[ 'id' => '0408', 'name' => 'La Uniòn', 'departamentos_id' => '04' ]
            ,[ 'id' => '0501', 'name' => 'Huamanga', 'departamentos_id' => '05' ]
            ,[ 'id' => '0502', 'name' => 'Cangallo', 'departamentos_id' => '05' ]
            ,[ 'id' => '0503', 'name' => 'Huanca Sancos', 'departamentos_id' => '05' ]
            ,[ 'id' => '0504', 'name' => 'Huanta', 'departamentos_id' => '05' ]
            ,[ 'id' => '0505', 'name' => 'La Mar', 'departamentos_id' => '05' ]
            ,[ 'id' => '0506', 'name' => 'Lucanas', 'departamentos_id' => '05' ]
            ,[ 'id' => '0507', 'name' => 'Parinacochas', 'departamentos_id' => '05' ]
            ,[ 'id' => '0508', 'name' => 'Pàucar del Sara Sara', 'departamentos_id' => '05' ]
            ,[ 'id' => '0509', 'name' => 'Sucre', 'departamentos_id' => '05' ]
            ,[ 'id' => '0510', 'name' => 'Víctor Fajardo', 'departamentos_id' => '05' ]
            ,[ 'id' => '0511', 'name' => 'Vilcas Huamán', 'departamentos_id' => '05' ]
            ,[ 'id' => '0601', 'name' => 'Cajamarca', 'departamentos_id' => '06' ]
            ,[ 'id' => '0602', 'name' => 'Cajabamba', 'departamentos_id' => '06' ]
            ,[ 'id' => '0603', 'name' => 'Celendín', 'departamentos_id' => '06' ]
            ,[ 'id' => '0604', 'name' => 'Chota', 'departamentos_id' => '06' ]
            ,[ 'id' => '0605', 'name' => 'Contumazá', 'departamentos_id' => '06' ]
            ,[ 'id' => '0606', 'name' => 'Cutervo', 'departamentos_id' => '06' ]
            ,[ 'id' => '0607', 'name' => 'Hualgayoc', 'departamentos_id' => '06' ]
            ,[ 'id' => '0608', 'name' => 'Jaén', 'departamentos_id' => '06' ]
            ,[ 'id' => '0609', 'name' => 'San Ignacio', 'departamentos_id' => '06' ]
            ,[ 'id' => '0610', 'name' => 'San Marcos', 'departamentos_id' => '06' ]
            ,[ 'id' => '0611', 'name' => 'San Miguel', 'departamentos_id' => '06' ]
            ,[ 'id' => '0612', 'name' => 'San Pablo', 'departamentos_id' => '06' ]
            ,[ 'id' => '0613', 'name' => 'Santa Cruz', 'departamentos_id' => '06' ]
            ,[ 'id' => '0701', 'name' => 'Prov. Const. del Callao', 'departamentos_id' => '07' ]
            ,[ 'id' => '0801', 'name' => 'Cusco', 'departamentos_id' => '08' ]
            ,[ 'id' => '0802', 'name' => 'Acomayo', 'departamentos_id' => '08' ]
            ,[ 'id' => '0803', 'name' => 'Anta', 'departamentos_id' => '08' ]
            ,[ 'id' => '0804', 'name' => 'Calca', 'departamentos_id' => '08' ]
            ,[ 'id' => '0805', 'name' => 'Canas', 'departamentos_id' => '08' ]
            ,[ 'id' => '0806', 'name' => 'Canchis', 'departamentos_id' => '08' ]
            ,[ 'id' => '0807', 'name' => 'Chumbivilcas', 'departamentos_id' => '08' ]
            ,[ 'id' => '0808', 'name' => 'Espinar', 'departamentos_id' => '08' ]
            ,[ 'id' => '0809', 'name' => 'La Convención', 'departamentos_id' => '08' ]
            ,[ 'id' => '0810', 'name' => 'Paruro', 'departamentos_id' => '08' ]
            ,[ 'id' => '0811', 'name' => 'Paucartambo', 'departamentos_id' => '08' ]
            ,[ 'id' => '0812', 'name' => 'Quispicanchi', 'departamentos_id' => '08' ]
            ,[ 'id' => '0813', 'name' => 'Urubamba', 'departamentos_id' => '08' ]
            ,[ 'id' => '0901', 'name' => 'Huancavelica', 'departamentos_id' => '09' ]
            ,[ 'id' => '0902', 'name' => 'Acobamba', 'departamentos_id' => '09' ]
            ,[ 'id' => '0903', 'name' => 'Angaraes', 'departamentos_id' => '09' ]
            ,[ 'id' => '0904', 'name' => 'Castrovirreyna', 'departamentos_id' => '09' ]
            ,[ 'id' => '0905', 'name' => 'Churcampa', 'departamentos_id' => '09' ]
            ,[ 'id' => '0906', 'name' => 'Huaytará', 'departamentos_id' => '09' ]
            ,[ 'id' => '0907', 'name' => 'Tayacaja', 'departamentos_id' => '09' ]
            ,[ 'id' => '1001', 'name' => 'Huánuco', 'departamentos_id' => '10' ]
            ,[ 'id' => '1002', 'name' => 'Ambo', 'departamentos_id' => '10' ]
            ,[ 'id' => '1003', 'name' => 'Dos de Mayo', 'departamentos_id' => '10' ]
            ,[ 'id' => '1004', 'name' => 'Huacaybamba', 'departamentos_id' => '10' ]
            ,[ 'id' => '1005', 'name' => 'Huamalíes', 'departamentos_id' => '10' ]
            ,[ 'id' => '1006', 'name' => 'Leoncio Prado', 'departamentos_id' => '10' ]
            ,[ 'id' => '1007', 'name' => 'Marañón', 'departamentos_id' => '10' ]
            ,[ 'id' => '1008', 'name' => 'Pachitea', 'departamentos_id' => '10' ]
            ,[ 'id' => '1009', 'name' => 'Puerto Inca', 'departamentos_id' => '10' ]
            ,[ 'id' => '1010', 'name' => 'Lauricocha ', 'departamentos_id' => '10' ]
            ,[ 'id' => '1011', 'name' => 'Yarowilca ', 'departamentos_id' => '10' ]
            ,[ 'id' => '1101', 'name' => 'Ica ', 'departamentos_id' => '11' ]
            ,[ 'id' => '1102', 'name' => 'Chincha ', 'departamentos_id' => '11' ]
            ,[ 'id' => '1103', 'name' => 'Nasca ', 'departamentos_id' => '11' ]
            ,[ 'id' => '1104', 'name' => 'Palpa ', 'departamentos_id' => '11' ]
            ,[ 'id' => '1105', 'name' => 'Pisco ', 'departamentos_id' => '11' ]
            ,[ 'id' => '1201', 'name' => 'Huancayo ', 'departamentos_id' => '12' ]
            ,[ 'id' => '1202', 'name' => 'Concepción ', 'departamentos_id' => '12' ]
            ,[ 'id' => '1203', 'name' => 'Chanchamayo ', 'departamentos_id' => '12' ]
            ,[ 'id' => '1204', 'name' => 'Jauja ', 'departamentos_id' => '12' ]
            ,[ 'id' => '1205', 'name' => 'Junín ', 'departamentos_id' => '12' ]
            ,[ 'id' => '1206', 'name' => 'Satipo ', 'departamentos_id' => '12' ]
            ,[ 'id' => '1207', 'name' => 'Tarma ', 'departamentos_id' => '12' ]
            ,[ 'id' => '1208', 'name' => 'Yauli ', 'departamentos_id' => '12' ]
            ,[ 'id' => '1209', 'name' => 'Chupaca ', 'departamentos_id' => '12' ]
            ,[ 'id' => '1301', 'name' => 'Trujillo ', 'departamentos_id' => '13' ]
            ,[ 'id' => '1302', 'name' => 'Ascope ', 'departamentos_id' => '13' ]
            ,[ 'id' => '1303', 'name' => 'Bolívar ', 'departamentos_id' => '13' ]
            ,[ 'id' => '1304', 'name' => 'Chepén ', 'departamentos_id' => '13' ]
            ,[ 'id' => '1305', 'name' => 'Julcán ', 'departamentos_id' => '13' ]
            ,[ 'id' => '1306', 'name' => 'Otuzco ', 'departamentos_id' => '13' ]
            ,[ 'id' => '1307', 'name' => 'Pacasmayo ', 'departamentos_id' => '13' ]
            ,[ 'id' => '1308', 'name' => 'Pataz ', 'departamentos_id' => '13' ]
            ,[ 'id' => '1309', 'name' => 'Sánchez Carrión ', 'departamentos_id' => '13' ]
            ,[ 'id' => '1310', 'name' => 'Santiago de Chuco ', 'departamentos_id' => '13' ]
            ,[ 'id' => '1311', 'name' => 'Gran Chimú ', 'departamentos_id' => '13' ]
            ,[ 'id' => '1312', 'name' => 'Virú ', 'departamentos_id' => '13' ]
            ,[ 'id' => '1401', 'name' => 'Chiclayo ', 'departamentos_id' => '14' ]
            ,[ 'id' => '1402', 'name' => 'Ferreñafe ', 'departamentos_id' => '14' ]
            ,[ 'id' => '1403', 'name' => 'Lambayeque ', 'departamentos_id' => '14' ]
            ,[ 'id' => '1501', 'name' => 'Lima ', 'departamentos_id' => '15' ]
            ,[ 'id' => '1502', 'name' => 'Barranca ', 'departamentos_id' => '15' ]
            ,[ 'id' => '1503', 'name' => 'Cajatambo ', 'departamentos_id' => '15' ]
            ,[ 'id' => '1504', 'name' => 'Canta ', 'departamentos_id' => '15' ]
            ,[ 'id' => '1505', 'name' => 'Cañete ', 'departamentos_id' => '15' ]
            ,[ 'id' => '1506', 'name' => 'Huaral ', 'departamentos_id' => '15' ]
            ,[ 'id' => '1507', 'name' => 'Huarochirí ', 'departamentos_id' => '15' ]
            ,[ 'id' => '1508', 'name' => 'Huaura ', 'departamentos_id' => '15' ]
            ,[ 'id' => '1509', 'name' => 'Oyón ', 'departamentos_id' => '15' ]
            ,[ 'id' => '1510', 'name' => 'Yauyos ', 'departamentos_id' => '15' ]
            ,[ 'id' => '1601', 'name' => 'Maynas ', 'departamentos_id' => '16' ]
            ,[ 'id' => '1602', 'name' => 'Alto Amazonas ', 'departamentos_id' => '16' ]
            ,[ 'id' => '1603', 'name' => 'Loreto ', 'departamentos_id' => '16' ]
            ,[ 'id' => '1604', 'name' => 'Mariscal Ramón Castilla ', 'departamentos_id' => '16' ]
            ,[ 'id' => '1605', 'name' => 'Requena ', 'departamentos_id' => '16' ]
            ,[ 'id' => '1606', 'name' => 'Ucayali ', 'departamentos_id' => '16' ]
            ,[ 'id' => '1607', 'name' => 'Datem del Marañón ', 'departamentos_id' => '16' ]
            ,[ 'id' => '1608', 'name' => 'Putumayo', 'departamentos_id' => '16' ]
            ,[ 'id' => '1701', 'name' => 'Tambopata ', 'departamentos_id' => '17' ]
            ,[ 'id' => '1702', 'name' => 'Manu ', 'departamentos_id' => '17' ]
            ,[ 'id' => '1703', 'name' => 'Tahuamanu ', 'departamentos_id' => '17' ]
            ,[ 'id' => '1801', 'name' => 'Mariscal Nieto ', 'departamentos_id' => '18' ]
            ,[ 'id' => '1802', 'name' => 'General Sánchez Cerro ', 'departamentos_id' => '18' ]
            ,[ 'id' => '1803', 'name' => 'Ilo ', 'departamentos_id' => '18' ]
            ,[ 'id' => '1901', 'name' => 'Pasco ', 'departamentos_id' => '19' ]
            ,[ 'id' => '1902', 'name' => 'Daniel Alcides Carrión ', 'departamentos_id' => '19' ]
            ,[ 'id' => '1903', 'name' => 'Oxapampa ', 'departamentos_id' => '19' ]
            ,[ 'id' => '2001', 'name' => 'Piura ', 'departamentos_id' => '20' ]
            ,[ 'id' => '2002', 'name' => 'Ayabaca ', 'departamentos_id' => '20' ]
            ,[ 'id' => '2003', 'name' => 'Huancabamba ', 'departamentos_id' => '20' ]
            ,[ 'id' => '2004', 'name' => 'Morropón ', 'departamentos_id' => '20' ]
            ,[ 'id' => '2005', 'name' => 'Paita ', 'departamentos_id' => '20' ]
            ,[ 'id' => '2006', 'name' => 'Sullana ', 'departamentos_id' => '20' ]
            ,[ 'id' => '2007', 'name' => 'Talara ', 'departamentos_id' => '20' ]
            ,[ 'id' => '2008', 'name' => 'Sechura ', 'departamentos_id' => '20' ]
            ,[ 'id' => '2101', 'name' => 'Puno ', 'departamentos_id' => '21' ]
            ,[ 'id' => '2102', 'name' => 'Azángaro ', 'departamentos_id' => '21' ]
            ,[ 'id' => '2103', 'name' => 'Carabaya ', 'departamentos_id' => '21' ]
            ,[ 'id' => '2104', 'name' => 'Chucuito ', 'departamentos_id' => '21' ]
            ,[ 'id' => '2105', 'name' => 'El Collao ', 'departamentos_id' => '21' ]
            ,[ 'id' => '2106', 'name' => 'Huancané ', 'departamentos_id' => '21' ]
            ,[ 'id' => '2107', 'name' => 'Lampa ', 'departamentos_id' => '21' ]
            ,[ 'id' => '2108', 'name' => 'Melgar ', 'departamentos_id' => '21' ]
            ,[ 'id' => '2109', 'name' => 'Moho ', 'departamentos_id' => '21' ]
            ,[ 'id' => '2110', 'name' => 'San Antonio de Putina ', 'departamentos_id' => '21' ]
            ,[ 'id' => '2111', 'name' => 'San Román ', 'departamentos_id' => '21' ]
            ,[ 'id' => '2112', 'name' => 'Sandia ', 'departamentos_id' => '21' ]
            ,[ 'id' => '2113', 'name' => 'Yunguyo ', 'departamentos_id' => '21' ]
            ,[ 'id' => '2201', 'name' => 'Moyobamba ', 'departamentos_id' => '22' ]
            ,[ 'id' => '2202', 'name' => 'Bellavista ', 'departamentos_id' => '22' ]
            ,[ 'id' => '2203', 'name' => 'El Dorado ', 'departamentos_id' => '22' ]
            ,[ 'id' => '2204', 'name' => 'Huallaga ', 'departamentos_id' => '22' ]
            ,[ 'id' => '2205', 'name' => 'Lamas ', 'departamentos_id' => '22' ]
            ,[ 'id' => '2206', 'name' => 'Mariscal Cáceres ', 'departamentos_id' => '22' ]
            ,[ 'id' => '2207', 'name' => 'Picota ', 'departamentos_id' => '22' ]
            ,[ 'id' => '2208', 'name' => 'Rioja ', 'departamentos_id' => '22' ]
            ,[ 'id' => '2209', 'name' => 'San Martín ', 'departamentos_id' => '22' ]
            ,[ 'id' => '2210', 'name' => 'Tocache ', 'departamentos_id' => '22' ]
            ,[ 'id' => '2301', 'name' => 'Tacna ', 'departamentos_id' => '23' ]
            ,[ 'id' => '2302', 'name' => 'Candarave ', 'departamentos_id' => '23' ]
            ,[ 'id' => '2303', 'name' => 'Jorge Basadre ', 'departamentos_id' => '23' ]
            ,[ 'id' => '2304', 'name' => 'Tarata ', 'departamentos_id' => '23' ]
            ,[ 'id' => '2401', 'name' => 'Tumbes ', 'departamentos_id' => '24' ]
            ,[ 'id' => '2402', 'name' => 'Contralmirante Villar ', 'departamentos_id' => '24' ]
            ,[ 'id' => '2403', 'name' => 'Zarumilla ', 'departamentos_id' => '24' ]
            ,[ 'id' => '2501', 'name' => 'Coronel Portillo ', 'departamentos_id' => '25' ]
            ,[ 'id' => '2502', 'name' => 'Atalaya ', 'departamentos_id' => '25' ]
            ,[ 'id' => '2503', 'name' => 'Padre Abad ', 'departamentos_id' => '25' ]
            ,[ 'id' => '2504', 'name' => 'Purús', 'departamentos_id' => '25' ]
        ];
        DB::table('provinces')->insert($data);
    }
}
